### PR TITLE
Unquote component in plugin array

### PR DESCRIPTION
**Pull request by gregorybleiker**
In the in install code 
```
if (opts.plugins) {
    const param = { $q, queues, Vue, cfg }
    Object.keys(opts.plugins).forEach(key => {
      const p = opts.plugins[key]
      if (typeof p.install === 'function' && p !== Platform) {
        p.install(param)
      }
    })
 ```
p should be an object. If it is a string, the plugin is not loaded.

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update
- [ x] Provided documentation update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x ] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [x ] It's submitted to the `dev` branch and _not_ the `master` branch
- [x ] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix: #xxx[,#xxx]`, where "xxx" is the issue number)
- [ x] It's been tested with all major browsers

If adding a **new feature**, the PR's description includes:
- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

**Other information:**

### CODE REVIEW

**Comment by rstoenescu** [comment]
`quasar.conf.js` is parsed and CLI generates a .js file where it imports those plugins/components/directives. The `framework` object is not fed directly :)

The way it works now is correct.

**Comment by gregorybleiker** [comment]
Ah, ok... however this causes problems when using vue cli... there are several issues there, but I had to invoke this by calling it in the main.ts (with TypeScript)
```
Vue.use(Quasar, {
  plugins: [Loading],
})
```
and in this scenario, you definitely need to use it without quotes. So it maybe should be highlighted that the quasar.conf.js is processed, and if you want to pass an actual options property, it must look differently.

**Comment by rstoenescu** [comment]
Correct usage with vue cli. It's in docs. Notice the three tabs on the "Installation" section (one is for Vue CLI):

```js
import {
  Quasar,
  Loading
} from 'quasar'

Vue.use(Quasar, {
  plugins: {
    Loading
  },
  config: {
    loading: { /* Loading defaults */ }
  }
})
```

**Comment by gregorybleiker** [comment]
Sorry, I'm having a hard time finding this section? Where is this in the docs?

**Comment by rstoenescu** [comment]
https://v1.quasar-framework.org/quasar-plugins/loading

You've PRed into v1, but I'm starting to think you are on v0.17? Regardless, the install should work the same.

**Comment by gregorybleiker** [comment]
Ah yes, very nice... we'll have to switch to 1.0 at some point... still using 0.17

**Pull request closed without merging**
